apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: github-service
  name: github-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-service
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: github-service
    spec:
      containers:
      - name: github-service
        image: github-service:flux-v1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        env:
          - name: GITHUB_USER
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: user
          - name: GITHUB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: password
        resources: {}
