apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-search-ui
  labels:
    app: repo-search-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: repo-search-ui
  template:
    metadata:
      labels:
        app: repo-search-ui
    spec:
      containers:
      - name: repo-search-ui
        image: kudohn/repo-search-ui:flux-v1
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
          - name: nginx-volume
            mountPath: /etc/nginx/conf.d
            readOnly: true
        livenessProbe:
          initialDelaySeconds: 3
          timeoutSeconds: 3
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          initialDelaySeconds: 3
          timeoutSeconds: 3
          httpGet:
            path: /health
            port: 80
        resources: {}
      volumes:
      - name: nginx-volume
        configMap: 
          name: nginx-config
