bases:
- ../../base
patchesStrategicMerge: []
resources:
- ingress.yaml
namespace: dev
namePrefix: flux-
configMapGenerator:
- name: api-gateway-config
  literals:
  - serviceURL=http://flux-github-service.dev.svc.cluster.local/github
  - redisHost=redis-master.redis.svc.cluster.local
  - redisPort=6379