bases:
- ../../base
patchesStrategicMerge: []
resources:
- ingress.yaml
namespace: dev
namePrefix: flux-
configMapGenerator:
- name: api-gateway-config
  literals:
  - serviceURL=http://flux-github-service.default.svc.cluster.local/github
  - redisHost=redis-master.redis.svc.cluster.local
  - redisPort=6379
images:
- name: api-gateway
  newName: kudohn/api-gateway
  newTag: v1.2
- name: github-service
  newName: kudohn/github-service
  newTag: v1.2
- name: repo-search-ui
  newName: kudohn/repo-search-ui
  newTag: v1.2