---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-api-gateway
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-github-service
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-repo-search-ui
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
