---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-service
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-search-ui
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
