---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.api-gateway: glob:flux-*
  name: flux-api-gateway
  namespace: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.github-service: glob:flux-*
  name: flux-github-service
  namespace: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.repo-search-ui: glob:flux-*
  name: flux-repo-search-ui
  namespace: dev
