---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  annotations:
    fluxcd.io/automated: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-service
  annotations:
    fluxcd.io/automated: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-search-ui
  annotations:
    fluxcd.io/automated: "true"
