apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-gateway
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: kudohn/api-gateway:flux-v1
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 3
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
        env:
          - name: SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: api-gateway-config
                key: serviceURL
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: api-gateway-config
                key: redisHost
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: api-gateway-config
                key: redisPort
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: password
        resources: {}
